// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxpHiscXwnyAGtRlJbRFrDG62F8WOSIc',
    appId: '1:1089966125607:web:cad58af9f07a6a118d1402',
    messagingSenderId: '1089966125607',
    projectId: 'almuerzo-saludable',
    authDomain: 'almuerzo-saludable.firebaseapp.com',
    storageBucket: 'almuerzo-saludable.firebasestorage.app',
    measurementId: 'G-HKWNBTZ2V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAp9IX0swSyXDeXD9xi-C4DwP7lHQP2RE',
    appId: '1:1089966125607:android:88846c1c530076938d1402',
    messagingSenderId: '1089966125607',
    projectId: 'almuerzo-saludable',
    storageBucket: 'almuerzo-saludable.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJfiJMaRGCZFHI0Tpbh-hjhYYue_CfTDg',
    appId: '1:1089966125607:ios:dc5826c3a1bee84a8d1402',
    messagingSenderId: '1089966125607',
    projectId: 'almuerzo-saludable',
    storageBucket: 'almuerzo-saludable.firebasestorage.app',
    iosBundleId: 'com.example.domiYa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJfiJMaRGCZFHI0Tpbh-hjhYYue_CfTDg',
    appId: '1:1089966125607:ios:dc5826c3a1bee84a8d1402',
    messagingSenderId: '1089966125607',
    projectId: 'almuerzo-saludable',
    storageBucket: 'almuerzo-saludable.firebasestorage.app',
    iosBundleId: 'com.example.domiYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxpHiscXwnyAGtRlJbRFrDG62F8WOSIc',
    appId: '1:1089966125607:web:b41da99e6151b1fd8d1402',
    messagingSenderId: '1089966125607',
    projectId: 'almuerzo-saludable',
    authDomain: 'almuerzo-saludable.firebaseapp.com',
    storageBucket: 'almuerzo-saludable.firebasestorage.app',
    measurementId: 'G-XF0ES4RDCZ',
  );

}